### ISSUE TITLE
body부분과 footer 간격

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/prototype2#1]
http://sda.slowalk.net/browse/

body부분과 footer 간격을 좀 해결하면 좋겠습니다.

**Comment by mozodev** [comment]
간격을 적당히 좀 벌이자는 말씀?

**Comment by woonjjang** [comment]
푸터 위에 여백이 좀 있으면 좋겠어요. 지정이 안 되어 있는 듯

**Comment by mozodev** [comment]
https://github.com/sda17dev/prototype2/commit/f2f2d66ba92eb6c189b8a0bd1b79bf4e982e60c3
