### ISSUE TITLE
기술계층 - 하위 부분의 꺽쇄 부분에 backgroud를 조절할 수 있도록 수정한다.

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/prototype2#11]
<img width="299" alt="2017-08-30 8 21 40" src="https://user-images.githubusercontent.com/6022883/29849187-1dd2e170-8d60-11e7-98e9-dfa49fc3acb5.png">

**Comment by css3studio** [comment]
수정하였습니다!
기존에 이미지로 처리한 것을, css3을 사용하여 삼각형 모양을 만드는 방법으로 변경하였습니다.
