### ISSUE TITLE
GNB 검색에 디자인 도움없이 해당 검색 Select 버튼을 만들 수 있을까요 ?

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/prototype2#2]
![2017-08-08 6 23 22](https://user-images.githubusercontent.com/6022883/29065452-1b8a9052-7c67-11e7-9869-e10f871a8cd8.png)

**Comment by mozodev** [comment]
뭐 이정도야... ㅎ

**Comment by woonjjang** [comment]
역시 !!

**Comment by mozodev** [comment]
그냥 대강... ㅎ https://github.com/sda17dev/prototype2/commit/bc568eb4889e6d8e3b2786cd9e6932121d58be1a

**Comment by woonjjang** [comment]
검색창에 글을 삽입하는 박스처럼 line color만 줘서 영역을 구분만 하면 좋겠네요. 
<img width="108" alt="2017-08-11 10 34 58" src="https://user-images.githubusercontent.com/6022883/29198671-1a8de44e-7e81-11e7-806f-838a5c60dc67.png">
