### ISSUE TITLE
우단을 사용하는 기술계층의 세부보기 페이지를 보여준다.

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/prototype2#7]
- 탐색 컨텍스트를 제공한다. 
- 제목이 노출된다. 
- 컴포넌트가 노출된다. / 컴포넌트를 다운할 수 있다. 
- 컴포넌트가 없는 경우 어떻게 기록에 접근할 수 있는지 안내한다.(Guide)
- 메타정보가 보여진다. 
(검색을 통해 세부로 접근했을 때는 같은 위계에 해당되는 항목들을 이동할 수 있다. - 웹, 모바일)

**Comment by woonjjang** [comment]
![default](https://user-images.githubusercontent.com/6022883/29606858-716e8090-882a-11e7-87e3-2fe01f5460c5.png)

**Comment by woonjjang** [comment]
![screencapture-national-archives-optimalworkshop-chalkmark-qq345l38-tasks-1500607793169](https://user-images.githubusercontent.com/6022883/30419651-1d882a2c-9972-11e7-8f5d-0755201c971b.png)

@mozodev bootstrap 페이로 구성 부탁드립니다. 
detail.html 가 교체 대상입니다.

**Comment by woonjjang** [comment]
Title과 Reference사이에 http://discovery.nationalarchives.gov.uk/details/r/C14576 여기 나오는 검색창도 넣어주세요.

**Comment by mozodev** [comment]
892a0461e81e56bdf243263ffd06f2fe4d4577fb
